# Generated by Django 4.1.2 on 2022-12-03 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("p_ck", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="student", name="subject_id",),
        migrations.RemoveField(model_name="subjects", name="subject_id",),
        migrations.DeleteModel(name="Professor",),
        migrations.DeleteModel(name="Student",),
        migrations.DeleteModel(name="Subjects",),
    ]
