# Generated by Django 4.1.1 on 2022-12-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Iot_professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stu_name", models.CharField(max_length=200)),
                ("cur_date", models.DateTimeField()),
            ],
        ),
    ]
