# Generated by Django 4.1.1 on 2022-12-01 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_iot_professors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iot',
            name='iot_manager',
        ),
        migrations.DeleteModel(
            name='Iot_professor',
        ),
        migrations.DeleteModel(
            name='Iot',
        ),
        migrations.DeleteModel(
            name='Iot_Manager',
        ),
    ]
