# Generated by Django 4.1.1 on 2022-12-02 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0005_check_time_professor_table_student_table_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="check_times",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_id", models.IntegerField()),
                ("face_id", models.IntegerField()),
                ("pfr", models.IntegerField()),
                ("c_date", models.DateTimeField()),
                ("out_times", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="professor_tables",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("professor_id", models.IntegerField()),
                ("professor_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="student_tables",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.IntegerField()),
                ("student_name", models.CharField(max_length=200)),
                ("student_count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="subject_tables",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_id", models.IntegerField()),
                ("subject_name", models.CharField(max_length=200)),
                ("professor_id", models.IntegerField()),
                ("total_time", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(name="check_time",),
        migrations.RemoveField(model_name="student_table", name="student_id",),
        migrations.DeleteModel(name="professor_table",),
        migrations.DeleteModel(name="student_table",),
        migrations.DeleteModel(name="subject_table",),
        migrations.AddField(
            model_name="student_tables",
            name="subject_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="iot.subject_tables"
            ),
        ),
        migrations.AddField(
            model_name="professor_tables",
            name="subject_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="iot.subject_tables"
            ),
        ),
    ]
