# Generated by Django 4.1.1 on 2022-12-02 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iot", "0006_check_times_professor_tables_student_tables_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professor_tables",
            name="professor_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
