# Generated by Django 4.1.2 on 2022-12-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0009_alter_subject_tables_professor_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="student_tables",
            name="f_c",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="student_tables",
            name="p_c",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="student_tables",
            name="r_c",
            field=models.IntegerField(default=0),
        ),
    ]
